[package]
name = "txl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm-window = { path = "../crossterm-window"}
crossterm = "0.26"
unicode-width = "0.1"
